# Generated by Django 4.2.1 on 2023-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termos_de_uso", models.TextField(default="Termos de uso")),
            ],
            options={
                "verbose_name": "Configurações do site",
                "verbose_name_plural": "Configurações do site",
            },
        ),
    ]
