# Generated by Django 4.2.1 on 2023-07-08 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horario_inicio", models.TimeField(verbose_name="Horário Início")),
                ("horario_termino", models.TimeField(verbose_name="Horário Término")),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="reservas.sala"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
