# Generated by Django 4.2.1 on 2023-07-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservas", "0002_sala_ativo_reserva"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigAgendaSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, verbose_name="Nome")),
                (
                    "horario_abertura",
                    models.TimeField(verbose_name="Horário Abertura da Sala"),
                ),
                (
                    "horario_encerramento",
                    models.TimeField(verbose_name="Horário Encerramento da Sala"),
                ),
                (
                    "duracao_minima_reserva",
                    models.PositiveSmallIntegerField(
                        verbose_name="Duração em minutos miníma pra reserva"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="data",
        ),
        migrations.AlterField(
            model_name="reserva",
            name="horario_inicio",
            field=models.DateTimeField(verbose_name="Horário Início"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="horario_termino",
            field=models.DateTimeField(verbose_name="Horário Término"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
