# Generated by Django 4.2.1 on 2023-07-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0003_configagendasala_remove_reserva_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reservas.configagendasala",
            ),
        ),
    ]
