# Generated by Django 4.2.1 on 2023-07-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0004_sala_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="config",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="reservas.configagendasala",
            ),
        ),
    ]
