# Generated by Django 4.2.1 on 2023-07-15 14:58

from django.db import migrations, models
import django.db.models.deletion
import reservas.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0005_alter_sala_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
            ],
        ),
        migrations.AlterField(
            model_name="sala",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET(reservas.models.get_config_padrao),
                to="reservas.configagendasala",
            ),
        ),
        migrations.AddField(
            model_name="sala",
            name="unidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reservas.unidade",
            ),
        ),
    ]
