# Generated by Django 4.2.1 on 2023-07-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0006_unidade_alter_sala_config_sala_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reservas.unidade"
            ),
        ),
    ]
