# Generated by Django 4.2.1 on 2023-07-15 15:04

from django.db import migrations, models
import reservas.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0007_alter_sala_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="config",
            field=models.ForeignKey(
                on_delete=models.SET(reservas.models.get_config_padrao),
                to="reservas.configagendasala",
            ),
        ),
    ]
