# Generated by Django 4.2.1 on 2023-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0009_unidade_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
