# Generated by Django 4.2.1 on 2023-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0010_sala_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidade",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
