# Generated by Django 4.2.1 on 2023-09-02 14:15

from django.db import migrations, models
import django.db.models.deletion
import reservas.models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0011_unidade_ativo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reserva",
            options={"ordering": ["sala", "horario_inicio"]},
        ),
        migrations.AddField(
            model_name="reserva",
            name="titulo",
            field=models.CharField(default="", max_length=50, verbose_name="Título"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reserva",
            name="sala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="todas_reservas",
                to="reservas.sala",
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="imagem",
            field=models.ImageField(
                upload_to=reservas.models.get_path_sala_imagem, verbose_name="Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="sala",
            name="unidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="todas_salas",
                to="reservas.unidade",
            ),
        ),
    ]
